### ISSUE TITLE
What tool is that?

### ISSUE THREAD

**Issue by slackmoehrle** [Sumolari/MawKit#4]
In README.md, Item 1, after you type a terminal command you see an Apple Logo and a blue bar that gives cwd and milliseconds.

**Comment by Sumolari** [comment]
It's [Oh My ZSH](https://github.com/robbyrussell/oh-my-zsh) with [Powerlevel9k theme](https://github.com/bhilburn/powerlevel9k) and some modifications to [show last command runtime](https://coderwall.com/p/kmchbw/zsh-display-commands-runtime-in-prompt).
